config/routes.rb
Rails.application.routes.draw do

 devise_for :users do
 
  get '/users/sign_out' => 'devise/sessions#destroy'
  get '/users/sign_in' => 'devise/sessions#new'

end

  resources :loans
  resources :customers
  resources :quotes
  resources :cars
  resources :employees
  
  get 'pdf_pages', :to => 'pdf_pages#show', format: 'pdf'

  resources :roles do
    member do
      get 'descriptions'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # comment
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :employee
  belongs_to :car
  
    def vehicle_markup
    self.total_amount = (car.wholesale_price * 0.082)
  end

  def sales_tax
    self.total_amount = (vehicle_markup + car.wholesale_price) * 0.043
  end

  def total_cost
    self.total_amount = (car.wholesale_price + vehicle_markup + sales_tax)
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
# commented out because line #4 takes care of this in Cancancan --->  before_action :set_car, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource
	
  # GET /quotes
  # GET /quotes.json
  def index
#    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  
 
 def show

    respond_to do |format|
      format.html
      format.pdf 	  do

     render pdf: "Customer Quote",
     template: "quotes/show.pdf.erb",
     layout: 'pdf'


      end

    end

end

   

  # GET /quotes/new
  def new
#    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
#    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:sales_person, :vin, :make, :model, :color, :sale_price, :employee_id, :car_id)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_with(model: quote, local: true) do |form| %>
  <% if quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sales_person %>
    <%= form.text_field :sales_person %>
  </div>

  <div class="field">
    <%= form.label :vin %>
    <%= form.text_field :vin %>
  </div>

  <div class="field">
    <%= form.label :make %>
    <%= form.text_field :make %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :sale_price %>
    <%= form.text_field :sale_price %>
  </div>

  <div class="field">
   <%= form.label :employee_id %>
    <%= form.collection_select :employee_id, Employee.all, :id, :combinedemployeename%>   
  </div>
  
  <div class="field">
   <%= form.label :car_id %>
    <%= form.collection_select :car_id, Car.all, :id, :combinedcarname%>   
  </div>
  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Sales person</th>
      <th>Vin</th>
      <th>Make</th>
      <th>Model</th>
      <th>Color</th>
      <th>Sale price</th>
      <th>Employee</th>
      <th>Car</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.sales_person %></td>
        <td><%= quote.vin %></td>
        <td><%= quote.make %></td>
        <td><%= quote.model %></td>
        <td><%= quote.color %></td>
        <td><%= number_to_currency(quote.sale_price) %></td>
        <td><%= quote.employee.employee_first_name %>
		<%= quote.employee.employee_last_name %>
        
        <td><%= quote.car.model %>
		<%= quote.car.make %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
	  
	  
	     <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p>
  <strong>Sales person:</strong>
  <%= @quote.sales_person %>
</p>

<p>
  <strong>Vin:</strong>
  <%= @quote.vin %>
</p>

<p>
  <strong>Make:</strong>
  <%= @quote.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @quote.model %>
</p>

<p>
  <strong>Color:</strong>
  <%= @quote.color %>
</p>

<p>
  <strong>Sale price:</strong>
  <%= @quote.sale_price %>
</p>
<p>
  <strong>Employee:</strong>
  <%= @quote.employee.employee_first_name %>
    <%= @quote.employee.employee_last_name %>
</p>

<p>
  <strong>Car:</strong>
  <%= @quote.car.model %>
  <%= @quote.car.make %>

</p>
<p><%= link_to "Generate Quote(PDF)", quote_path(:quote_id =>@id, :format => 'pdf', popup:true) %></p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/show.pdf.erb
 <center><h1>Customer Quote</h1></center>
  
  <p>
  <strong>Sales person:</strong>
  <%= @quote.sales_person %>
</p>

<p>
  <strong>Vin:</strong>
  <%= @quote.vin %>
</p>

<p>
  <strong>Make:</strong>
  <%= @quote.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @quote.model %>
</p>

<p>
  <strong>Color:</strong>
  <%= @quote.color %>
</p>

<p>
  <strong>Sale price:</strong>
  <%= @quote.sale_price %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @quote.employee.employee_first_name %>
    <%= @quote.employee.employee_last_name %>
</p>

<p>
  <strong>Car:</strong>
   <%= @quote.car.model %>
  <%= @quote.car.make %>
</p>