config/routes.rb
Rails.application.routes.draw do

 devise_for :users do
 
  get '/users/sign_out' => 'devise/sessions#destroy'
  get '/users/sign_in' => 'devise/sessions#new'

end

  resources :loans
  resources :customers
  resources :quotes
  resources :cars
  resources :employees
  
  get 'pdf_pages', :to => 'pdf_pages#show', format: 'pdf'

  resources :roles do
    member do
      get 'descriptions'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # comment
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :role
  
  def combinedemployeename
    "#{employee_first_name} #{employee_last_name}"
	end
  
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
# commented out because line #4 takes care of this in Cancancan --->  before_action :set_car, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource
	

  # GET /employees
  # GET /employees.json
  def index
#    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
 #   @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
 #   @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:employee_first_name, :employee_last_name, :email, :role_id)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :employee_first_name %>
    <%= form.text_field :employee_first_name %>
  </div>

  <div class="field">
    <%= form.label :employee_last_name %>
    <%= form.text_field :employee_last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :role_id %>
    <%= form.collection_select :role_id, Role.all,:id,:role %>
      <br/>
    <p> Description: <span id ="descriptions"></span></p>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>Employee first name</th>
      <th>Employee last name</th>
      <th>Email</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.employee_first_name %></td>
        <td><%= employee.employee_last_name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.role.role %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p>
  <strong>Employee first name:</strong>
  <%= @employee.employee_first_name %>
</p>

<p>
  <strong>Employee last name:</strong>
  <%= @employee.employee_last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Role:</strong>
  <%= @employee.role.role %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>