config/routes.rb
Rails.application.routes.draw do

 devise_for :users do
 
  get '/users/sign_out' => 'devise/sessions#destroy'
  get '/users/sign_in' => 'devise/sessions#new'

end

  resources :loans
  resources :customers
  resources :quotes
  resources :cars
  resources :employees
  
  get 'pdf_pages', :to => 'pdf_pages#show', format: 'pdf'

  resources :roles do
    member do
      get 'descriptions'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # comment
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projectcis4339</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track'=> 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> 'reload' %>
  </head>
  <body>
  <div id='header'>
  <h1>Project 4339</h1>
  
  <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
  

  <%= link_to "Car", cars_path %>
  <%= link_to "Customer", customers_path %>
  <%= link_to "Employee", employees_path %>
  <%= link_to "Loan", loans_path %>
  <%= link_to "Quote", quotes_path %>
  <%= link_to "Role", roles_path %>
  </div>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<center><h1> Customer Quote </center></h1>
<title>Customer Quote</title>
  <%= wicked_pdf_stylesheet_link_tag "quotes" -%>
</head>
<body>
  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>